png(filename = "plot3.png",height = 480,width=480)
with(power,plot(DateTime,Sub_metering_1, ylab = "Energy sub metering",type="n"))
with(power,lines(DateTime,Sub_metering_1))
with(power,lines(DateTime,Sub_metering_2,col="red"))
with(power,lines(DateTime,Sub_metering_3,col="blue"))
legend("topright",lwd = c(1,1,1), col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()